_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.11.0
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 55
                - 71
                - 98
            "2":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 55
                - 71
                - 98
            "3":
                - 16
                - 23
                - 55
            "4": 3.11.0
            "5": 0.19.8
            "6": 4.40.1
            "8":
                - 5
            "12": 0.19.8
            "13": linux-x86_64
batch_size:
    value: null
epochs:
    value: 1
